         //1	
	 INSERT INTO picker (name, type, director, time, date, overview, link, photo,rating,year,release) VALUES('Drunk Parents', 'Comedy','Fred Wolf', '1h 37min', '19-04-2019','Two drunk parents attempt to hide their ever increasing financial difficulties from their daughter and social circle through elaborate neighborhood schemes.','https://youtu.be/6XdkzKSCcU4' , 'https://m.media-amazon.com/images/M/MV5BNTZkOTQ1NmMtYmY3Ni00NmI3LWI0MmEtNWQxODU3YjYxNTRkXkEyXkFqcGdeQXVyNzI1NzMxNzM@._V1_SY1000_SX675_AL_.jpg','high',2019,recent )
	 //2
	 INSERT INTO picker (name, type, director, time, date, overview, link, photo,rating,year,release) VALUES('Blue Streak', 'Comedy', 'Les Mayfiel', '1h 33min', '17-09-1999', 'A former convict poses as a cop to retrieve a diamond he stole years ago.', 'https://youtu.be/TrwRAT5LtoM', 'https://m.media-amazon.com/images/M/MV5BYTJkYTBlZjktYmYyYi00ZWQ0LTgyMWYtMjQ5Yzg1Y2M3YzE5XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SY1000_CR0,0,670,1000_AL_.jpg','high',1999,old)
	 //3
	 INSERT INTO picker (name, type, director, time, date, overview, link, photo,rating,year,release) VALUES('Game Night', 'Comedy', 'John Daley', '1h 40min', '23-02-2018', 'A group of friends who meet regularly for game nights find themselves entangled in a real-life mystery when the shady brother of one of them is seemingly kidnapped by dangerous gangsters.','https://youtu.be/qmxMAdV6s4U','https://m.media-amazon.com/images/M/MV5BMjI3ODkzNDk5MF5BMl5BanBnXkFtZTgwNTEyNjY2NDM@._V1_SY1000_CR0,0,674,1000_AL_.jpg','high',2018,new)
	 //4
	 INSERT INTO picker (name, type, director, time, date, overview, link, photo,rating,year,release) VALUES('Murder Mystery','Comedy','Kyle Newacheck','1h 37min','14-05-2019','A New York cop and his wife go on a European vacation to reinvigorate the spark in their marriage, but end up getting framed and on the run for the death of an elderly billionaire.','https://youtu.be/5YEVQDr2f3Q','https://m.media-amazon.com/images/M/MV5BNTA2YTI5YjUtZWI4Zi00NWQ5LWFiYmEtOTBmNTUyNDAwNjllXkEyXkFqcGdeQXVyNjIzNzM4NzA@._V1_SY1000_CR0,0,675,1000_AL_.jpg','mid',2019,recent)
	 //5
	 INSERT INTO picker (name, type, director, time, date, overview, link, photo,rating,year,release) VALUES('The Terminal', 'Comedy', 'Steven Spielberg', '2h 8min', '18-05-2004', 'An Eastern European tourist unexpectedly finds himself stranded in JFK airport, and must take up temporary residence there.','https://youtu.be/GZjC9dAvWuU','https://m.media-amazon.com/images/M/MV5BMTM1MTIwNTMxOF5BMl5BanBnXkFtZTcwNjIxMjQyMw@@._V1_SY1000_CR0,0,737,1000_AL_.jpg','mid',2004,old)
	 //6
	 INSERT INTO picker (name, type, director, time, date, overview, link, photo,rating,year,release) VALUES('Going In Style', 'Comedy','Zach Braff','1h 36min', '07-04-2017','Desperate to pay the bills and come through for their loved ones, three lifelong pals risk it all by embarking on a daring bid to knock off the very bank that absconded with their money.','https://youtu.be/hcdTN5soeQw','https://m.media-amazon.com/images/M/MV5BMTc5Mzg3NjI4OF5BMl5BanBnXkFtZTgwNzA3Mzg4MDI@._V1_SY1000_CR0,0,674,1000_AL_.jpg','mid',2017,new)
	 //7
	 INSERT INTO picker (name, type, director, time, date, overview, link, photo,rating,year,release) VALUES('The Upside', 'Comedy','Neil Burger','2h 6min','11-01-2019','A comedic look at the relationship between a wealthy man with quadriplegia and an unemployed man with a criminal record whos hired to help him.','https://youtu.be/EWw7rCHcduQ','https://m.media-amazon.com/images/M/MV5BNzY3NzYyNjI0N15BMl5BanBnXkFtZTgwNjYzMDc0NjM@._V1_SY1000_CR0,0,674,1000_AL_.jpg','low',2019,recent)
	 //8
	 INSERT INTO picker (name, type, director, time, date, overview, link, photo,rating,year,release) VALUES('Paul Blart: Mall Cop','Comedy','Steve Carr','1h 31min','16-01-2009','When a shopping mall is taken over by a gang of organized crooks, its up to a mild-mannered security guard to save the day.','https://youtu.be/dfzmYp60I7w','https://m.media-amazon.com/images/M/MV5BMTM2NzA1MzE1NF5BMl5BanBnXkFtZTcwOTYyNDIzMg@@._V1_.jpg','low',2009,old)
	 //9
	 INSERT INTO picker (name, type, director, time, date, overview, link, photo,rating,year,release) VALUES('Night School', 'Comedy', 'Malcom Lee', '1h 51min', '28-09-2018', 'A group of high school dropouts are forced to attend night school in hope that theyll pass the GED exam to finish high school.','https://youtu.be/t9QtXGirWf0','https://m.media-amazon.com/images/M/MV5BYzEyYzg5N2YtZmYzZC00OTg0LWE3ZmYtNDZhMGFkOTBjOTYxXkEyXkFqcGdeQXVyNDg2MjUxNjM@._V1_SY1000_CR0,0,631,1000_AL_.jpg','low',2018,new)
	 //10
	 INSERT INTO picker (name, type, director, time, date, overview, link, photo,rating,year,release) VALUES('Crawl','Horror','Alexandre Aja','1h 27min','12-07-2019','A young woman, while attempting to save her father during a category 5 hurricane, finds herself trapped in a flooding house and must fight for her life against alligators.','https://www.youtube.com/watch?v=H6MLJG0RdDE','https://m.media-amazon.com/images/M/MV5BNTk4MTliYzgtOGI2Ni00N2I5LTg4MjktZTkzZTE0MWVjNGEyXkEyXkFqcGdeQXVyMTA3MTA4Mzgw._V1_SY1000_CR0,0,666,1000_AL_.jpg','high',2019,recent)
	 //11
	 INSERT INTO picker (name, type, director, time, date, overview, link, photo,rating,year,release) VALUES('Paranormal Activity','Horror','Oren Peli','1h 26min','16-10-2007','After moving into a suburban home, a couple becomes increasingly disturbed by a nightly demonic presence.','https://youtu.be/F_UxLEqd074','https://m.media-amazon.com/images/M/MV5BMjY1NjcxODQ4MV5BMl5BanBnXkFtZTcwMzUxNjM4Mg@@._V1_SY1000_CR0,0,674,1000_AL_.jpg','high',2007,old)
	 //12
	 INSERT INTO picker (name, type, director, time, date, overview, link, photo,rating,year,release) VALUES('The Nun','Horror','Corin Hardy','1h 36min','7-09-2018','A priest with a haunted past and a novice on the threshold of her final vows are sent by the Vatican to investigate the death of a young nun in Romania and confront a malevolent force in the form of a demonic nun.','https://youtu.be/pzD9zGcUNrw','https://m.media-amazon.com/images/M/MV5BMjM3NzQ5NDcxOF5BMl5BanBnXkFtZTgwNzM4MTQ5NTM@._V1_SY1000_CR0,0,674,1000_AL_.jpg','high',2018,new)
	 //13
	 INSERT INTO picker (name, type, director, time, date, overview, link, photo,rating,year,release) VALUES('IT Chapter Two','Horror','Andy Muschietti','2h 49min','06-09-2019','Twenty-seven years after their first encounter with the terrifying Pennywise, the Losers Club have grown up and moved away, until a devastating phone call brings them back.','https://www.youtube.com/watch?v=xhJ5P7Up3jA','https://m.media-amazon.com/images/M/MV5BYTJlNjlkZTktNjEwOS00NzI5LTlkNDAtZmEwZDFmYmM2MjU2XkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_SY1000_CR0,0,674,1000_AL_.jpg','mid',2019,recent)
	 //14
	 INSERT INTO picker (name, type, director, time, date, overview, link, photo,rating,year,release) VALUES('Saw','Horror','James Wan','1h 43min','29-10-2004','Two strangers, who awaken in a room with no recollection of how they got there, soon discover theyre pawns in a deadly game perpetrated by a notorious serial killer.','https://www.youtube.com/watch?v=S-1QgOMQ-ls','https://m.media-amazon.com/images/M/MV5BMjE4MDYzNDE1OV5BMl5BanBnXkFtZTcwNDY2OTYwNA@@._V1_SY1000_SX675_AL_.jpg','mid',2004,old)
	 //15
	 INSERT INTO picker (name, type, director, time, date, overview, link, photo,rating,year,release) VALUES('The Purge: Election Year','Horror','James DeMonaco','1h 48min','01-06-2016','Former Police Sergeant Barnes becomes head of security for Senator Charlie Roan, a Presidential candidate targeted for death on Purge night due to her vow to eliminate the Purge.','https://www.youtube.com/watch?v=RXMp9fBomJw','https://m.media-amazon.com/images/M/MV5BMjI3MDI0MTA1N15BMl5BanBnXkFtZTgwOTk4NjU5ODE@._V1_SY1000_CR0,0,675,1000_AL_.jpg','mid',2016,new)
	 //16
	 INSERT INTO picker (name, type, director, time, date, overview, link, photo,rating,year,release) VALUES('Annabelle Comes Home','Horror','Gary Dauberman','1h 46min','26-06-2019','While babysitting the daughter of Ed and Lorraine Warren, a teenager and her friend unknowingly awaken an evil spirit trapped in a doll.','https://www.youtube.com/watch?v=bCxm7cTpBAs','https://m.media-amazon.com/images/M/MV5BYmI4NDNiMmQtZTFkYi00ZDVmLThlYTAtMWJlMjU1M2I2ZmViXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_SY1000_CR0,0,674,1000_AL_.jpg','low',2019,recent)
	 //17
	 INSERT INTO picker (name, type, director, time, date, overview, link, photo,rating,year,release) VALUES('Seed of Chucky','Horror','Don Mancini','1h 27min','12-11-2004','Chucky and Tiffany are resurrected by their innocent gender confused Daughter, Glenda, and hit Hollywood, where a movie depicting the killer dolls murder spree is underway.','https://www.youtube.com/watch?v=CKc-mP5xXQY','https://m.media-amazon.com/images/M/MV5BMTIwMTczMjc3M15BMl5BanBnXkFtZTcwODcxMzcyMQ@@._V1_SY1000_CR0,0,641,1000_AL_.jpg','low',2004,old)
	 //18
	 INSERT INTO picker (name, type, director, time, date, overview, link, photo,rating,year,release) VALUES('Oujia','Horror','Stiles White','1h 29min','24-10-2014','A group of friends must confront their most terrifying fears when they awaken the dark powers of an ancient spirit board.','https://www.youtube.com/watch?v=_T1Jj1inE8M','https://m.media-amazon.com/images/M/MV5BMTQ1NzcwMTU5MF5BMl5BanBnXkFtZTgwOTE5MzEyMjE@._V1_SY1000_CR0,0,631,1000_AL_.jpg','low',2016,new)
	 //19
	 INSERT INTO picker (name, type, director, time, date, overview, link, photo,rating,year,release) VALUES('Avengers: EndGame','Action','Joe Russo','3h 1min','26-04-2019','the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos actions and restore balance to the universe.','https://www.youtube.com/watch?v=5Eyw-Qiwpj0','https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SY1000_CR0,0,674,1000_AL_.jpg','high',2019,recent)
	 //20
	 INSERT INTO picker (name, type, director, time, date, overview, link, photo,rating,year,release) VALUES('The Italian Job','Action','Gary Gary','1h 51min','30-05-2003','After being betrayed and left for dead in Italy, Charlie Croker and his team plan an elaborate gold heist against their former ally.','https://www.youtube.com/watch?v=5Eyw-Qiwpj0','https://m.media-amazon.com/images/M/MV5BNDYyNzYxNjYtNmYzMC00MTE0LWIwMmYtNTAyZDBjYTIxMTRhXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SY1000_CR0,0,666,1000_AL_.jpg','high',2003,old)
	 //21
	 INSERT INTO picker (name, type, director, time, date, overview, link, photo,rating,year,release) VALUES('White House Down','Action','Roland Emmerich','2h 11min','28-05-2013','While on a tour of the White House with his young daughter, a Capitol policeman springs into action to save his child and protect the president from a heavily armed group of paramilitary invaders.','https://www.youtube.com/watch?v=WfaTlmYvTA8','https://m.media-amazon.com/images/M/MV5BMTAyNzQyNTcwNjVeQTJeQWpwZ15BbWU3MDAwOTQ4Nzk@._V1_SY1000_CR0,0,676,1000_AL_.jpg','high',2013,new)
	 //22
	 INSERT INTO picker (name, type, director, time, date, overview, link, photo,rating,year,release) VALUES('Joker','Action','Todd Phillips','2h 2min','4-10-2019','In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker.','https://www.youtube.com/watch?v=zAGVQLHvwOY','https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SY1000_CR0,0,674,1000_AL_.jpg','mid',2019,recent)
	 //23
	 INSERT INTO picker (name, type, director, time, date, overview, link, photo,rating,year,release) VALUES('The Karate Kid','Action','Harald Zwart','2h 20min','11-05-2010','Work causes a single mother to move to China with her young son; in his new home, the boy embraces kung fu, taught to him by a master.','https://www.youtube.com/watch?v=XY8amUImEu0','https://m.media-amazon.com/images/M/MV5BMTQ0ODg3ODEyMF5BMl5BanBnXkFtZTcwNjI1MTgxMw@@._V1_SY1000_CR0,0,675,1000_AL_.jpg','mid',2010,old)
	 //24
	 INSERT INTO picker (name, type, director, time, date, overview, link, photo,rating,year,release) VALUES('Pain & Gain','Action','Michael Bay','2h 9min','26-04-2013','A trio of bodybuilders in Florida get caught up in an extortion ring and a kidnapping scheme that goes terribly wrong.','https://www.youtube.com/watch?v=SEQ8jyvmYtw','https://m.media-amazon.com/images/M/MV5BMTU0NDE5NTU0OV5BMl5BanBnXkFtZTcwMzI1OTMzOQ@@._V1_SY1000_SX678_AL_.jpg','mid',2013,new)
	 //25
	 INSERT INTO picker (name, type, director, time, date, overview, link, photo,rating,year,release) VALUES('John Wick Chapter 3','Action','Chad Stahelski','2h 11min','17-05-2019','John Wick is on the run after killing a member of the international assassins guild, and with a $14 million price tag on his head, he is the target of hit men and women everywhere.','https://www.youtube.com/watch?v=pU8-7BX9uxs','https://m.media-amazon.com/images/M/MV5BMDg2YzI0ODctYjliMy00NTU0LTkxODYtYTNkNjQwMzVmOTcxXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_SY1000_CR0,0,648,1000_AL_.jpg','low',2019,recent)
	 //26
	 INSERT INTO picker (name, type, director, time, date, overview, link, photo,rating,year,release) VALUES('The Dark Knight','Action','Christopher Nolan','2h 32min','18-07-2008','When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.','https://www.youtube.com/watch?v=EXeTwQWrcwY','https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SY1000_CR0,0,675,1000_AL_.jpg','low',2008,old)
	 //27
	 INSERT INTO picker (name, type, director, time, date, overview, link, photo,rating,year,release) VALUES('True Memoirs of an International Assassin','Action','Jeff Wadlow','1h 39min','11-11-2016','After a publisher changes a writers debut novel about a deadly assassin from fiction to non-fiction, the author finds himself thrust into the world of his lead character, and must take on the role of his character for his own survival.','https://www.youtube.com/watch?v=E6l4xrEjFY8','https://m.media-amazon.com/images/M/MV5BMjEzMjI0Mzc5MV5BMl5BanBnXkFtZTgwODExMDgxMDI@._V1_SY1000_CR0,0,674,1000_AL_.jpg','low',2016,new)